### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by Yozhef** [jpvdw86/symfony-health-check-bundle#1]
@jpvdw86 I see you really [liked our solution](https://packagist.org/packages/macpaw/symfony-health-check-bundle), but you decided to publish it with minor changes - tell me why you decided not to use our solution?

https://packagist.org/packages/macpaw/symfony-health-check-bundle

I found this in [you](https://github.com/jpvdw86/symfony-health-check-bundle/commit/8151a5d90630c1f64f93e72a2622cacf69220ac3) - maybe you just need to write us an issue and steps for reproducing?
+ Anyway, if you want to further develop this library on your own - please make a fork of ours - to have links to the main project

8151a5d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R5

**Comment by Yozhef** [comment]
I think it's not cool to steal decisions without changes and just add your name everywhere) 
Despite the fact that this project is actively supported and ready to always listen to your ideas for change

**Comment by Yozhef** [comment]
@jpvdw86

**Comment by Yozhef** [comment]
https://github.com/jpvdw86/symfony-health-check-bundle/commit/8151a5d90630c1f64f93e72a2622cacf69220ac3#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R5

**Comment by jpvdw86** [comment]
Did you look closely at the changes?

It is correct that the base of your project is used and as been changed. However, I had to make significant changes to get to my desired functionality

Think of getting the doctrine health check working. Your versions was old solution that not worked any more (see that you have already made changes to this)

In addition the response code, if not heathy (on some checks) is not 200. This make easy to force restart a docker container. Check docs for example

This behavior is a choice and there will be a reason why you are not doing this. therefore Is chose to do a separate project for my own.

Cheers
